import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { ConfigContext, ExpoConfig } from 'expo/config';
import { ConfigPlugin, withGradleProperties } from 'expo/config-plugins';
import pkg from './package.json';

// EAS Android release builds die with `OutOfMemoryError: Metaspace` on the
// default Gradle heap (`-Xmx2048m -XX:MaxMetaspaceSize=512m`) — the native-dep
// set (Expo modules, Sentry, FB SDK, Google Sign-In, ...) overruns it. android/
// is regenerated by `expo prebuild --clean`, so this can't be a hand-edit
// there; it has to be a config plugin that re-applies on every prebuild.
// (Same fix as chunky-crayon / salt-mammal.)
const GRADLE_JVMARGS = '-Xmx6144m -XX:MaxMetaspaceSize=1024m';

const withGradleHeap: ConfigPlugin = (config) =>
  withGradleProperties(config, (cfg) => {
    const existing = cfg.modResults.find(
      (item) => item.type === 'property' && item.key === 'org.gradle.jvmargs',
    );
    if (existing && existing.type === 'property') {
      existing.value = GRADLE_JVMARGS;
    } else {
      cfg.modResults.push({
        type: 'property',
        key: 'org.gradle.jvmargs',
        value: GRADLE_JVMARGS,
      });
    }
    return cfg;
  });

// Per-variant app identity (fleet standard — same as GU / PTP / Salt Mammal).
// EXPO_PUBLIC_ENVIRONMENT is set per EAS build profile so dev / preview / prod
// produce different names + icons (+ bundle ids) and can install side-by-side.
const env = process.env.EXPO_PUBLIC_ENVIRONMENT || 'development';

const appName =
  env === 'production'
    ? "Auntie Marlene's"
    : env === 'preview'
      ? 'AM Internal'
      : 'AM Dev';

const bundleId =
  env === 'production'
    ? 'com.chewybytes.auntiemarlenes.app'
    : env === 'preview'
      ? 'com.chewybytes.auntiemarlenes.app.internal'
      : 'com.chewybytes.auntiemarlenes.app.dev';

export default ({ config }: ConfigContext): ExpoConfig => {
  const variantSuffix =
    env === 'production' ? '' : env === 'preview' ? '-preview' : '-dev';
  const pickIcon = (base: string): string => {
    const variantPath = `./assets/images/${base}${variantSuffix}.png`;
    return existsSync(join(__dirname, variantPath))
      ? variantPath
      : `./assets/images/${base}.png`;
  };

  const expoConfig: ExpoConfig = {
    ...config,
    name: appName,
    slug: 'auntie-marlenes',
    owner: 'chewybytes',
    version: pkg.version,
    orientation: 'portrait',
    icon: pickIcon('icon'),
    scheme: 'auntiemarlenes',
    userInterfaceStyle: 'light',
    ios: {
      bundleIdentifier: bundleId,
      supportsTablet: true,
      usesAppleSignIn: true,
      infoPlist: {
        ITSAppUsesNonExemptEncryption: false,
      },
    },
    android: {
      package: bundleId,
      adaptiveIcon: {
        foregroundImage: pickIcon('adaptive-icon'),
        backgroundColor: '#492C26',
      },
    },
    plugins: [
      'expo-router',
      'expo-dev-client',
      [
        'expo-splash-screen',
        {
          image: './assets/images/splash-icon.png',
          resizeMode: 'contain',
          backgroundColor: '#492C26',
        },
      ],
      [
        'expo-font',
        {
          fonts: [
            './assets/fonts/Inter18pt-Regular.ttf',
            './assets/fonts/Inter18pt-Bold.ttf',
            './assets/fonts/Inter18pt-SemiBold.ttf',
            './assets/fonts/Inter18pt-Medium.ttf',
            './assets/fonts/Inter18pt-Light.ttf',
            './assets/fonts/Inter18pt-Italic.ttf',
            './assets/fonts/Inter18pt-Black.ttf',
            './assets/fonts/Inter18pt-BlackItalic.ttf',
            './assets/fonts/Inter18pt-BoldItalic.ttf',
            './assets/fonts/Inter18pt-ExtraBold.ttf',
            './assets/fonts/Inter18pt-ExtraBoldItalic.ttf',
            './assets/fonts/Inter18pt-ExtraLight.ttf',
            './assets/fonts/Inter18pt-ExtraLightItalic.ttf',
            './assets/fonts/Inter18pt-LightItalic.ttf',
            './assets/fonts/Inter18pt-MediumItalic.ttf',
            './assets/fonts/Inter18pt-SemiBoldItalic.ttf',
            './assets/fonts/Inter18pt-Thin.ttf',
            './assets/fonts/Inter18pt-ThinItalic.ttf',
            './assets/fonts/PlayfairDisplay-Regular.ttf',
            './assets/fonts/PlayfairDisplay-Bold.ttf',
            './assets/fonts/PlayfairDisplay-SemiBold.ttf',
            './assets/fonts/PlayfairDisplay-Medium.ttf',
            './assets/fonts/PlayfairDisplay-Italic.ttf',
            './assets/fonts/PlayfairDisplay-Black.ttf',
            './assets/fonts/PlayfairDisplay-BlackItalic.ttf',
            './assets/fonts/PlayfairDisplay-BoldItalic.ttf',
            './assets/fonts/PlayfairDisplay-ExtraBold.ttf',
            './assets/fonts/PlayfairDisplay-ExtraBoldItalic.ttf',
            './assets/fonts/PlayfairDisplay-MediumItalic.ttf',
            './assets/fonts/PlayfairDisplay-SemiBoldItalic.ttf',
          ],
        },
      ],
      'expo-localization',
      [
        'react-native-fbsdk-next',
        {
          appID: `${process.env.EXPO_PUBLIC_FACEBOOK_APP_ID}`,
          displayName: "Auntie Marlene's",
          clientToken: `${process.env.EXPO_PUBLIC_FACEBOOK_CLIENT_TOKEN}`,
          scheme: 'auntiemarlenes',
        },
      ],
      [
        'expo-build-properties',
        {
          ios: {
            useFrameworks: 'static',
            deploymentTarget: '16.4',
          },
          android: {
            minSdkVersion: 23,
          },
        },
      ],
      [
        '@sentry/react-native/expo',
        {
          url: 'https://sentry.io/',
          project: 'auntie-marlenes-app',
          organization: 'chewybytes',
        },
      ],
    ],
    experiments: {
      typedRoutes: true,
    },
    runtimeVersion: {
      policy: 'appVersion',
    },
    extra: {
      eas: {
        projectId: '29cfb8ae-a3ed-40c5-9a9c-a83d839a28d1',
      },
    },
  };

  // Android-only: rewrites org.gradle.jvmargs on every prebuild. No-op on iOS.
  return withGradleHeap(expoConfig);
};
