import { COLORS } from '@auntie-marlenes/constants';
import type { Config } from 'tailwindcss';

export default {
  content: ['./app/**/*.{js,jsx,ts,tsx}', './components/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        // Brand colors
        'warm-sand': COLORS.warmSand,
        terracotta: COLORS.terracotta,
        'warm-clay': COLORS.warmClay,
        'sage-green': COLORS.sageGreen,
        'warm-beige': COLORS.warmBeige,
        cocoa: COLORS.cocoa,
        'deep-earth': COLORS.deepEarth,
        // UI colors
        background: COLORS.light.background,
        foreground: COLORS.light.foreground,
        card: COLORS.light.card,
        'card-foreground': COLORS.light.cardForeground,
        primary: COLORS.light.primary,
        'primary-foreground': COLORS.light.primaryForeground,
        secondary: COLORS.light.secondary,
        'secondary-foreground': COLORS.light.secondaryForeground,
        muted: COLORS.light.muted,
        'muted-foreground': COLORS.light.mutedForeground,
        accent: COLORS.light.accent,
        'accent-foreground': COLORS.light.accentForeground,
        destructive: COLORS.light.destructive,
        'destructive-foreground': COLORS.light.destructiveForeground,
        border: COLORS.light.border,
        input: COLORS.light.input,
        ring: COLORS.light.ring,
      },
      fontFamily: {
        // Inter variants
        inter: ['Inter18pt-Regular'],
        'inter-bold': ['Inter18pt-Bold'],
        'inter-semibold': ['Inter18pt-SemiBold'],
        'inter-medium': ['Inter18pt-Medium'],
        'inter-light': ['Inter18pt-Light'],
        'inter-italic': ['Inter18pt-Italic'],
        'inter-black': ['Inter18pt-Black'],
        'inter-black-italic': ['Inter18pt-BlackItalic'],
        'inter-bold-italic': ['Inter18pt-BoldItalic'],
        'inter-extrabold': ['Inter18pt-ExtraBold'],
        'inter-extrabold-italic': ['Inter18pt-ExtraBoldItalic'],
        'inter-extralight': ['Inter18pt-ExtraLight'],
        'inter-extralight-italic': ['Inter18pt-ExtraLightItalic'],
        'inter-light-italic': ['Inter18pt-LightItalic'],
        'inter-medium-italic': ['Inter18pt-MediumItalic'],
        'inter-semibold-italic': ['Inter18pt-SemiBoldItalic'],
        'inter-thin': ['Inter18pt-Thin'],
        'inter-thin-italic': ['Inter18pt-ThinItalic'],
        // Playfair Display variants
        playfair: ['PlayfairDisplay-Regular'],
        'playfair-bold': ['PlayfairDisplay-Bold'],
        'playfair-semibold': ['PlayfairDisplay-SemiBold'],
        'playfair-medium': ['PlayfairDisplay-Medium'],
        'playfair-italic': ['PlayfairDisplay-Italic'],
        'playfair-black': ['PlayfairDisplay-Black'],
        'playfair-black-italic': ['PlayfairDisplay-BlackItalic'],
        'playfair-bold-italic': ['PlayfairDisplay-BoldItalic'],
        'playfair-extrabold': ['PlayfairDisplay-ExtraBold'],
        'playfair-extrabold-italic': ['PlayfairDisplay-ExtraBoldItalic'],
        'playfair-medium-italic': ['PlayfairDisplay-MediumItalic'],
        'playfair-semibold-italic': ['PlayfairDisplay-SemiBoldItalic'],
      },
    },
  },
  plugins: [],
} satisfies Config;
